// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOwYAbBPKnVweRKZK7Xr4Jd6o36uiOXZY',
    appId: '1:337422546876:web:def75d420c060eed7c9db9',
    messagingSenderId: '337422546876',
    projectId: 'belajarbloc-b9152',
    authDomain: 'belajarbloc-b9152.firebaseapp.com',
    storageBucket: 'belajarbloc-b9152.firebasestorage.app',
    measurementId: 'G-91E8948YN2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoeRnQetwO_LDiMoYQ3Vd2XLSD2a0Wq2g',
    appId: '1:337422546876:android:4c07c6f24622a1be7c9db9',
    messagingSenderId: '337422546876',
    projectId: 'belajarbloc-b9152',
    storageBucket: 'belajarbloc-b9152.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb0q_Jp5-536Glx09UEf7rzDLnkIq0bMc',
    appId: '1:337422546876:ios:1ba1407da5cbf02c7c9db9',
    messagingSenderId: '337422546876',
    projectId: 'belajarbloc-b9152',
    storageBucket: 'belajarbloc-b9152.firebasestorage.app',
    iosBundleId: 'com.example.belajarBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb0q_Jp5-536Glx09UEf7rzDLnkIq0bMc',
    appId: '1:337422546876:ios:1ba1407da5cbf02c7c9db9',
    messagingSenderId: '337422546876',
    projectId: 'belajarbloc-b9152',
    storageBucket: 'belajarbloc-b9152.firebasestorage.app',
    iosBundleId: 'com.example.belajarBloc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOwYAbBPKnVweRKZK7Xr4Jd6o36uiOXZY',
    appId: '1:337422546876:web:fdd28b30c0be340d7c9db9',
    messagingSenderId: '337422546876',
    projectId: 'belajarbloc-b9152',
    authDomain: 'belajarbloc-b9152.firebaseapp.com',
    storageBucket: 'belajarbloc-b9152.firebasestorage.app',
    measurementId: 'G-TFHDQRH02S',
  );
}
